package agents

import (
	"fmt"
	"strings"
)

// SpecLayer is a single slice of context that will be composed into the
// final agent prompt.  Layers are ordered from most general to most specific.
type SpecLayer struct {
	Title   string // e.g. "Project Standards", "Task Context", "Step 3"
	Content string // Markdown body
	Source  string // "repo", "domain", "worktree", "step", "handoff"
}

// AgentSpec is the assembled set of context layers for an agent session.
type AgentSpec struct {
	Layers []SpecLayer
}

// NewAgentSpec creates an empty spec.
func NewAgentSpec() *AgentSpec {
	return &AgentSpec{Layers: make([]SpecLayer, 0)}
}

// AddLayer appends a layer to the spec.
func (s *AgentSpec) AddLayer(layer SpecLayer) {
	s.Layers = append(s.Layers, layer)
}

// AddLayerFromMarkdown parses a Markdown document and appends it as a single layer.
// This is useful for consuming the output of get_context.py.
func (s *AgentSpec) AddLayerFromMarkdown(md string) {
	md = strings.TrimSpace(md)
	if md == "" {
		return
	}
	s.Layers = append(s.Layers, SpecLayer{
		Title:   "Trellis Context",
		Content: md,
		Source:  "trellis",
	})
}

// ToMarkdown renders the full spec as a single Markdown document suitable
// for writing to AGENTS.md.
func (s *AgentSpec) ToMarkdown() string {
	var b strings.Builder

	b.WriteString("# Focus Agent Context\n\n")
	b.WriteString("> This file is auto-generated by Focus-tui. Do not edit manually.\n\n")

	for i, layer := range s.Layers {
		if i > 0 {
			b.WriteString("\n---\n\n")
		}
		if layer.Title != "" {
			b.WriteString(fmt.Sprintf("## %s\n\n", layer.Title))
		}
		b.WriteString(strings.TrimSpace(layer.Content))
		b.WriteString("\n")
	}

	return b.String()
}

// Summary returns a one-line description of what this spec contains.
func (s *AgentSpec) Summary() string {
	var parts []string
	for _, l := range s.Layers {
		if l.Title != "" {
			parts = append(parts, l.Title)
		}
	}
	if len(parts) == 0 {
		return "empty spec"
	}
	return strings.Join(parts, " → ")
}
